---
title: "The most ideal year"
author: "Markus Konrad"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)

theme_set(theme_minimal())
```


## TODOs

- write explanations
- proof-read
- update data
- remove this section
- deploy

## Data

source: https://www.dwd.de/DE/leistungen/klimadatendeutschland/klarchivtagmonat.html

```{r}
raw_hist <- read.delim('data/produkt_klima_tag_19500101_20221231_00403.txt', sep = ';')
head(raw_hist)
```

```{r}
raw_pres <- read.delim('data/produkt_klima_tag_20221107_20240509_00403.txt', sep = ';')
head(raw_pres)
```


```{r}
meas <- bind_rows(raw_hist, raw_pres) |>
    select(date = MESS_DATUM, temp = TMK) |>
    mutate(date = as.POSIXct(strptime(date, "%Y%m%d")),
           year = as.integer(as.numeric(format(date, "%Y"))),
           day = as.integer(as.numeric(format(date, "%j")))) |>
    distinct(date, .keep_all = TRUE)
rm(raw_hist, raw_pres)
stopifnot(all(count(meas, date)$n == 1))
head(meas)
```

```{r, message=FALSE, fig.width=10}
ggplot(meas, aes(date, temp)) +
    geom_line() +
    geom_smooth(method = "gam")
```

```{r}
filter(meas, year >= 2018) |>
    ggplot(aes(date, temp)) +
        geom_line()
```

```{r}
filter(meas, year == 2023) |>
    ggplot(aes(date, temp)) +
        geom_line() +
        geom_smooth()
```

```{r}
ggplot(meas, aes(day, temp, color = year)) +
    geom_point(alpha = 0.25) +
    scale_color_binned(type = 'viridis')
```

```{r}
m1 <- lm(temp ~ cos(2 * pi * day/366) + sin(2 * pi * day/366), meas)
summary(m1)
```

```{r}
plot(m1)
```

```{r}
meas_fit <- cbind(meas, pred = fitted(m1))

filter(meas_fit, year >= 2018) |>
    ggplot() +
        geom_line(aes(date, temp), alpha = 0.25) +
        geom_line(aes(date, pred), color = 'red')
```

```{r}
ggplot(meas_fit) +
    geom_line(aes(date, temp), alpha = 0.25) +
    geom_line(aes(date, pred), color = 'red')
```



```{r}
filter(meas_fit, year %in% (1950 + 0:6 * 10)) |>
    ggplot(aes(day, temp, color = year)) +
        geom_point(alpha = 0.25) +
        geom_line(aes(day, pred), color = 'red') +
        scale_color_binned(type = 'viridis')
        
```



```{r}
m2 <- lm(temp ~ year + cos(2 * pi * day/366) + sin(2 * pi * day/366), meas)
summary(m2)
```

```{r}
plot(m2)
```


```{r}
meas_fit2 <- cbind(meas, pred = fitted(m2))

filter(meas_fit2, year >= 2018) |>
    ggplot() +
        geom_line(aes(date, temp), alpha = 0.25) +
        geom_line(aes(date, pred), color = 'red')
```

```{r}
ggplot(meas_fit2) +
    geom_line(aes(date, temp), alpha = 0.25) +
    geom_line(aes(date, pred), color = 'red')
```


```{r}
filter(meas_fit2, year %in% (1950 + 0:6 * 10)) |>
    ggplot(aes(day, temp, color = year)) +
        geom_point(alpha = 0.25) +
        geom_line(aes(day, pred, color = year)) +
        scale_color_binned(type = 'viridis')
        
```

```{r}
resid <- meas_fit2$temp - meas_fit2$pred
ggplot(data.frame(resid = resid), aes(resid)) +
    geom_histogram(bins = 20)
```

```{r}
quantile(resid, c(0.05, 0.95))
```


```{r}
thresh_unusal_temp <- 6

resid_stats <- group_by(meas_fit2, year) |>
    summarise(me = mean(temp - pred),
              mae = mean(abs(temp - pred)),
              prop_days_warmer = mean(temp > pred + thresh_unusal_temp),
              prop_days_colder = mean(temp < pred - thresh_unusal_temp))
              #rmse = sqrt(mean((temp - pred)^2)))
resid_stats
```

```{r}
resid_stats_plt <- pivot_longer(resid_stats, !year, names_to = "measure")

filter(resid_stats_plt, measure %in% c("mae", "me")) |>
    ggplot(aes(x = year, y = value, fill = measure)) +
        geom_col(position = position_dodge()) +
        facet_wrap(vars(measure), nrow = 2, scales = "free_y")
```


```{r}
filter(resid_stats_plt, measure %in% c("prop_days_warmer", "prop_days_colder")) |>
    ggplot(aes(x = year, y = value, fill = measure)) +
        geom_col(position = position_stack()) +
        scale_fill_discrete(limits = rev)
```



```{r}
resid_stats_ordered <- filter(resid_stats, year < 2024) |>
    arrange(mae)
resid_stats_ordered |> head(1)
```

```{r}
resid_stats_ordered |> tail(1)
```

```{r}
least_deviation_yr <- resid_stats_ordered |> head(1) |> pull(year)
most_deviation_yr <- resid_stats_ordered |> tail(1) |> pull(year)

least_most_plt <- data.frame(year = c(least_deviation_yr, most_deviation_yr), label = c("least deviation", "most deviation")) |>
    inner_join(meas_fit2, by = 'year') |>
    mutate(label = paste0(year, " (", label, ")"),
           resid = temp - pred,
           transparency = ifelse(abs(resid) > thresh_unusal_temp, 0.5, 0.1))

ggplot(least_most_plt, aes(day, temp, color = label)) +
    geom_point(aes(alpha = transparency)) +
    geom_line(aes(day, pred)) +
    scale_color_discrete(guide = guide_legend(title = NULL)) +
    scale_alpha_identity(guide = NULL)
```

```{r, fig.width=10}
ggplot(least_most_plt, aes(day, resid, color = label, alpha = transparency)) +
    geom_hline(yintercept = 0, linetype = "dashed") +
    geom_hline(yintercept = -thresh_unusal_temp, linetype = "dotted") +
    geom_hline(yintercept = thresh_unusal_temp, linetype = "dotted") +
    geom_point() +
    scale_color_discrete(guide = guide_legend(title = NULL)) +
    scale_alpha_identity(guide = NULL)
```

- probably remove this:

```{r}
least_most_baseline1985 <- mutate(
    least_most_plt,
    pred = ifelse(year == 2017, pred - (2017 - 1985) * m2$coefficients[2], pred),
    resid = temp - pred,
    transparency = ifelse(abs(resid) > thresh_unusal_temp, 0.5, 0.1))

ggplot(least_most_baseline1985, aes(day, temp, color = label)) +
    geom_point(aes(alpha = transparency)) +
    geom_line(aes(day, pred)) +
    scale_color_discrete(guide = guide_legend(title = NULL)) +
    scale_alpha_identity(guide = NULL)
```


